name: Test builder script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: [ubuntu-20.04, [self-hosted, Linux, ARM64]]
        stage: [unstable, testing, release]
        distro-codename: [ubuntu-focal, ubuntu-impish, ubuntu-jammy, debian-bullseye]
        include:
          - host-os: ubuntu-20.04
            arch: amd64
          - host-os: [self-hosted, Linux, ARM64]
            arch: arm64
          - distro-codename: ubuntu-focal
            distro: ubuntu
            codename: focal
          - distro-codename: ubuntu-impish
            distro: ubuntu
            codename: impish
          - distro-codename: ubuntu-jammy
            distro: ubuntu
            codename: jammy
          - distro-codename: debian-bullseye
            distro: debian
            codename: bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Set Job Parameters
        id: init
        run: |
          echo "MANIFEST_PATH=${{ github.workspace }}/manifests" >> $GITHUB_OUTPUT
          echo "PKG_REPO_PATH=${{ github.workspace }}/repo" >> $GITHUB_OUTPUT
          echo "PKG_BUILD_DIR=${{ github.workspace }}/packages" >> $GITHUB_OUTPUT
          echo "GH_REPO_ROOT=${{ github.workspace }}" >> $GITHUB_OUTPUT
          echo "stage=${{ matrix.stage }}" >> $GITHUB_OUTPUT
          echo "distro=${{ matrix.distro }}" >> $GITHUB_OUTPUT
          echo "codename=${{ matrix.codename }}" >> $GITHUB_OUTPUT
          echo "arch=${{ matrix.arch }}" >> $GITHUB_OUTPUT
          echo "target=${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT          
      - name: Clean tmp
        run: |
          set -x
          rm -Rf ${{ steps.init.outputs.PKG_REPO_PATH }} || true
          mkdir ${{ steps.init.outputs.PKG_REPO_PATH }}
          rm -Rf ${{ steps.init.outputs.MANIFEST_PATH }} || true
          mkdir ${{ steps.init.outputs.MANIFEST_PATH }}
          rm -Rf ${{ steps.init.outputs.PKG_BUILD_DIR }} || true
          mkdir ${{ steps.init.outputs.PKG_BUILD_DIR }}
      - name: Test Build
        run: |
          set -x
          ${{ github.workspace }}/.github/scripts/main.sh \
            "${{ github.workspace }}" \
            "${{ github.workspace }}/.github/scripts/ext-tester.sh" \
            "${{ steps.init.outputs.stage }}" \
            "${{ steps.init.outputs.distro }}" \
            "${{ steps.init.outputs.codename }}" \
            "${{ steps.init.outputs.arch }}" \
            test_repo_url \
            Default \
            check \
            ${{ steps.init.outputs.MANIFEST_PATH }} \
            ${{ steps.init.outputs.PKG_REPO_PATH }} \
            ${{ steps.init.outputs.PKG_BUILD_DIR }}
