name: regolith-desktop is installable 2

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-debian-bullseye-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable, testing] # , release
        distro-codename: [debian-bullseye]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, focal]
          - distro-codename: debian-bullseye
            distro: debian
            codename: bullseye
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-debian-bullseye-action@v1
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-debian-testing-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable] # , release
        distro-codename: [debian-testing]
        arch: [amd64] #, arm64]  // Need dedicated build host to build arm64
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - distro-codename: debian-testing
            distro: debian
            codename: testing
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-debian-testing-action@v1.1
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop ${{ matrix.wm }}"
  test-ubuntu-focal-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable, testing] #, release
        distro-codename: [ubuntu-focal]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, focal]
          - distro-codename: ubuntu-focal
            distro: ubuntu
            codename: focal
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-ubuntu-20.04-action@v1.1.5
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-ubuntu-jammy-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable, testing] #, release
        distro-codename: [ubuntu-jammy]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: ubuntu-22.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, jammy]
          - distro-codename: ubuntu-jammy
            distro: ubuntu
            codename: jammy
        exclude:
          - stage: testing # remove this after wayland enters testing
            wm: regolith-session-sway
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-ubuntu-22.04-action@v1.1.6
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop ${{ matrix.wm }}"
  test-ubuntu-lunar-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable] #, testing, release
        distro-codename: [ubuntu-lunar]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: ubuntu-23.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, lunar]
          - distro-codename: ubuntu-lunar
            distro: ubuntu
            codename: lunar
        exclude:
          - stage: testing # remove this after wayland enters testing
            wm: regolith-session-sway
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-ubuntu-lunar-action@1.0.0
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop ${{ matrix.wm }}"