name: regolith-desktop is installable 2

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-debian-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable] # , testing, release
        distro-codename: [debian-bullseye]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, focal]
          - distro-codename: debian-bullseye
            distro: debian
            codename: bullseye
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: kgilmer/test-debian-bullseye-action@v1
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-ubuntu-install:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable] # , testing, release
        distro-codename: [ubuntu-focal, ubuntu-jammy] #, ubuntu-kinetic]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, focal]
          - distro-codename: ubuntu-focal
            distro: ubuntu
            codename: focal
            action-name: kgilmer/test-ubuntu-20.04-action@v1.1.5
          - distro-codename: ubuntu-jammy
            distro: ubuntu
            codename: jammy
            action-name: kgilmer/test-ubuntu-22.04-action@v1.1.5
    steps:
      - name: Test ${{ matrix.stage }} ${{ matrix.distro-codename }} ${{ matrix.arch }}
        uses: ${{ matrix.action-name }}
        with:
          apt-key-url: http://regolith-desktop.org/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
